/**
 * GENERATED by `npm run devnet:setup` — do not edit by hand.
 *
 * Devnet stand-ins for each xStock. Backed and Backpack only deploy on mainnet,
 * so devnet runs use Token-2022 mints created by the setup script with the
 * same decimals and Scaled UI Amount multiplier as the real mint. They are
 * priced at the real mint's price. Public addresses, safe to commit.
 */

export const DEVNET_MINTS: Record<string, string> = {
  MCDx: '8JeMwAWAQi3Mnt1ZThxxUj3nksT1LaacZCfAKKADV9jt',
  AMZNx: 'AFfNYN1rcvcfBX4nX7gSxGAsg34WfEVuM5yiDJj4zQbq',
  NKE: 'GXBogsngSQKcb468nbrk9bQotoupnvZksWmCC1xDrGdy',
  COST: '4KCAryEaA5pyQkwbnXiARkVaDCSsc4MRtSDjbZ6tN5dz',
  LULU: 'EFbvE5TuA1sACJUiSbp4FwbRhwtVE3tH6WrBEkuW3ouF',
  NFLXx: '9qmm4qMd9NBQNB2FGNZtnEwBCPYsHah4PkHLw9RET96C',
  WMTx: '2fR9ysa7WsRG5qbYVKU7BPu5TFiPVA18rrTqE6imW8ZF',
  AAPLx: 'EMg5TdVCpcj4wxVUFGnXbTS8UccGCMgAfbNHF5wMoCG9',
};
